//! systemd-nspawn launcher script and systemd unit generation.
//!
//! This module is the heart of Nspawn Studio: it turns a ContainerConfig
//! into a fully self-contained, human readable bash launcher, plus an
//! optional systemd unit. Everything that depends on the live session
//! (DISPLAY, XAUTHORITY, XDG_RUNTIME_DIR, existing sockets) is resolved at
//! run time by the generated script, so a container can be started directly
//! from a terminal or through systemd with the very same file.

use crate::model::{BootMode, ContainerConfig, NetworkMode, OwnershipMode, X11Access};

/// POSIX single-quote escaping.
///
/// The result is safe to splice into a bash script: characters that have a
/// special meaning are wrapped in single quotes and embedded single quotes
/// are escaped.
pub fn shell_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }
    let safe = value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || "/._-:@%+=,~".contains(c));
    if safe {
        value.to_string()
    } else {
        let mut out = String::with_capacity(value.len() + 2);
        out.push('\'');
        for c in value.chars() {
            if c == '\'' {
                out.push_str("'\\''");
            } else {
                out.push(c);
            }
        }
        out.push('\'');
        out
    }
}

/// Expand a leading tilde using the current HOME.
pub fn expand_tilde(value: &str) -> String {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    if value == "~" {
        home
    } else if let Some(rest) = value.strip_prefix("~/") {
        format!("{}/{}", home.trim_end_matches('/'), rest)
    } else {
        value.to_string()
    }
}

fn comment_safe(value: &str) -> String {
    value.replace('\n', " ").replace('\r', " ")
}

fn line(out: &mut String, text: &str) {
    out.push_str(text);
    out.push('\n');
}

fn flag(out: &mut String, name: &str) {
    out.push_str("ARGS+=(");
    out.push_str(name);
    out.push_str(")\n");
}

/// Append ARGS+=(--name=<quoted literal value>)
fn flag_value(out: &mut String, name: &str, value: &str) {
    out.push_str("ARGS+=(--");
    out.push_str(name);
    out.push('=');
    out.push_str(&shell_quote(value));
    out.push_str(")\n");
}

/// Generate the full launcher script for a container.
pub fn generate_script(cfg: &ContainerConfig) -> String {
    let mut s = String::new();
    let machine = cfg.machine_name().to_string();
    let rootfs = cfg.rootfs.to_string_lossy().to_string();

    line(&mut s, "#!/usr/bin/env bash");
    line(
        &mut s,
        "# =============================================================================",
    );
    line(&mut s, "#  Nspawn Studio container launcher");
    line(&mut s, "#");
    line(&mut s, &format!("#  Container : {}", comment_safe(&cfg.name)));
    line(&mut s, &format!("#  Machine   : {}", comment_safe(&machine)));
    line(&mut s, &format!("#  Rootfs    : {}", comment_safe(&rootfs)));
    line(
        &mut s,
        &format!("#  Generated : {} (unix time)", crate::model::now_unix()),
    );
    line(&mut s, "#");
    line(
        &mut s,
        "#  Usage:  sudo <this script> [extra systemd-nspawn arguments]",
    );
    line(&mut s, "#");
    line(
        &mut s,
        "#  This file is generated by Nspawn Studio and is rewritten every time the",
    );
    line(
        &mut s,
        "#  container configuration is saved. Edit the container in the GUI instead.",
    );
    line(
        &mut s,
        "# =============================================================================",
    );
    line(&mut s, "set -euo pipefail");
    line(&mut s, "");
    line(&mut s, &format!("NAME={}", shell_quote(&machine)));
    line(&mut s, &format!("ROOTFS={}", shell_quote(&rootfs)));
    line(&mut s, "");
    line(&mut s, "# --- pre-flight checks ------------------------------------------------");
    line(&mut s, "if [[ \"${EUID:-$(id -u)}\" -ne 0 ]]; then");
    line(
        &mut s,
        "  echo \"nspawn-studio: this launcher must be run as root\" >&2",
    );
    line(&mut s, "  exit 1");
    line(&mut s, "fi");
    line(&mut s, "if [[ ! -d \"$ROOTFS\" ]]; then");
    line(
        &mut s,
        "  echo \"nspawn-studio: root filesystem not found: $ROOTFS\" >&2",
    );
    line(&mut s, "  exit 1");
    line(&mut s, "fi");
    line(&mut s, "if ! command -v systemd-nspawn >/dev/null 2>&1; then");
    line(
        &mut s,
        "  echo \"nspawn-studio: systemd-nspawn not found (install the systemd-container package)\" >&2",
    );
    line(&mut s, "  exit 1");
    line(&mut s, "fi");
    line(&mut s, "");
    line(&mut s, "# --- live session environment -----------------------------------------");
    line(&mut s, "HOST_UID=\"${NSPAWN_STUDIO_HOST_UID:-0}\"");
    line(&mut s, "RUNTIME_DIR=\"${XDG_RUNTIME_DIR:-/run/user/$HOST_UID}\"");
    line(&mut s, "HOST_HOME=\"${NSPAWN_STUDIO_HOST_HOME:-${HOME:-/root}}\"");
    line(&mut s, "XAUTH=\"${XAUTHORITY:-$HOST_HOME/.Xauthority}\"");
    line(&mut s, "DISPLAY_VALUE=\"${DISPLAY:-:0}\"");
    line(&mut s, "");
    line(&mut s, "# --- base -------------------------------------------------------------");
    line(&mut s, "ARGS=()");
    line(&mut s, "ARGS+=(\"--machine=$NAME\")");
    line(&mut s, "ARGS+=(\"--directory=$ROOTFS\")");

    // Console handling differs between interactive and service use.
    line(&mut s, "if [[ -n \"${NSPAWN_STUDIO_SERVICE:-}\" ]]; then");
    line(&mut s, "  ARGS+=(--console=read-only)");
    line(&mut s, "else");
    line(
        &mut s,
        &format!("  ARGS+=(--console={})", cfg.console.as_str()),
    );
    line(&mut s, "fi");

    if cfg.boot == BootMode::Boot {
        line(&mut s, "ARGS+=(-b)");
    }

    if let Some(hostname) = &cfg.hostname {
        if !hostname.is_empty() {
            flag_value(&mut s, "hostname", hostname);
        }
    }

    // --- hardening / sandboxing ---
    let sec = &cfg.security;
    if sec.private_users {
        flag(&mut s, "-U");
        if sec.ownership != OwnershipMode::Auto {
            flag_value(&mut s, "private-users-ownership", sec.ownership.as_str());
        }
    }
    if sec.read_only {
        flag(&mut s, "--read-only");
    }
    if sec.ephemeral {
        flag(&mut s, "--ephemeral");
    }
    if sec.no_new_privileges {
        flag_value(&mut s, "no-new-privileges", "yes");
    }
    for cap in &sec.drop_capabilities {
        flag_value(&mut s, "drop-capability", cap);
    }
    for cap in &sec.add_capabilities {
        flag_value(&mut s, "capability", cap);
    }
    for filter in &sec.system_call_filter {
        flag_value(&mut s, "system-call-filter", filter);
    }
    for path in &sec.mask {
        flag_value(&mut s, "inaccessible", path);
    }
    for path in &sec.tmpfs {
        flag_value(&mut s, "tmpfs", path);
    }

    // --- networking ---
    match cfg.network.mode {
        NetworkMode::Host => {}
        NetworkMode::Private => flag(&mut s, "--private-network"),
        NetworkMode::Veth => {
            flag(&mut s, "--network-veth");
            if let Some(bridge) = &cfg.network.bridge {
                if !bridge.is_empty() {
                    flag_value(&mut s, "network-bridge", bridge);
                }
            }
        }
    }
    if cfg.network.mode != NetworkMode::Host {
        for fwd in &cfg.network.port_forwards {
            flag_value(&mut s, "port", &fwd.to_arg());
        }
    }

    // --- resolv.conf / timezone ---
    flag_value(&mut s, "resolv-conf", cfg.resolv_conf.as_str());
    flag_value(&mut s, "timezone", cfg.timezone.as_str());

    // --- bind mounts ---
    for mount in &cfg.mounts {
        let host = expand_tilde(&mount.host);
        let spec = format!("{}:{}", host, mount.container);
        let flag_name = if mount.read_only { "bind-ro" } else { "bind" };
        flag_value(&mut s, flag_name, &spec);
    }

    // --- X11 ---
    if cfg.x11 != X11Access::None {
        line(&mut s, "# --- X11 ---");
        if cfg.x11 == X11Access::Xephyr {
            // A private nested X server: the host display only shows the
            // Xephyr window, the container gets its own display.
            line(&mut s, "if ! command -v Xephyr >/dev/null 2>&1; then");
            line(
                &mut s,
                "  echo \"nspawn-studio: Xephyr not found (install the xserver-xephyr package)\" >&2",
            );
            line(&mut s, "  exit 1");
            line(&mut s, "fi");
            line(&mut s, "HOST_DISPLAY=\"$DISPLAY_VALUE\"");
            line(&mut s, "XEPHYR_NUM=10");
            line(
                &mut s,
                "while [[ -e \"/tmp/.X11-unix/X$XEPHYR_NUM\" || -e \"/tmp/.X$XEPHYR_NUM-lock\" ]]; do",
            );
            line(&mut s, "  XEPHYR_NUM=$((XEPHYR_NUM + 1))");
            line(&mut s, "  if [[ $XEPHYR_NUM -gt 99 ]]; then");
            line(
                &mut s,
                "    echo \"nspawn-studio: no free X display for Xephyr\" >&2",
            );
            line(&mut s, "    exit 1");
            line(&mut s, "  fi");
            line(&mut s, "done");
            line(&mut s, "XEPHYR_DISPLAY=\":$XEPHYR_NUM\"");
            line(
                &mut s,
                &format!(
                    "Xephyr \"$XEPHYR_DISPLAY\" -screen {} -ac -noreset -title \"Nspawn Studio: $NAME\" >/dev/null 2>&1 &",
                    shell_quote(&cfg.xephyr_screen)
                ),
            );
            line(&mut s, "XEPHYR_PID=$!");
            line(&mut s, "for ((i = 0; i < 50; i++)); do");
            line(&mut s, "  [[ -e \"/tmp/.X11-unix/X$XEPHYR_NUM\" ]] && break");
            line(&mut s, "  sleep 0.1");
            line(&mut s, "done");
            line(&mut s, "if ! kill -0 \"$XEPHYR_PID\" 2>/dev/null; then");
            line(
                &mut s,
                "  echo \"nspawn-studio: Xephyr failed to start on host display $HOST_DISPLAY\" >&2",
            );
            line(&mut s, "  exit 1");
            line(&mut s, "fi");
            line(&mut s, "DISPLAY_VALUE=\"$XEPHYR_DISPLAY\"");
        }
        // --setenv only reaches PID 1. A booted container's login shells read
        // /etc/profile.d, so bind a generated snippet there as well; without
        // it, programs started after "login:" have no DISPLAY.
        line(
            &mut s,
            "RUN_ENV_DIR=\"${NSPAWN_STUDIO_RUN_DIR:-/run/nspawn-studio}\"",
        );
        line(&mut s, "mkdir -p \"$RUN_ENV_DIR\"");
        line(&mut s, "X11_ENV_FILE=\"$RUN_ENV_DIR/${NAME}-x11.sh\"");
        line(&mut s, "{");
        line(&mut s, "  echo '# generated by Nspawn Studio'");
        line(&mut s, "  echo \"export DISPLAY='$DISPLAY_VALUE'\"");
        if cfg.x11 == X11Access::Authority {
            line(
                &mut s,
                "  if [ -f \"$XAUTH\" ]; then echo 'export XAUTHORITY=/root/.Xauthority'; fi",
            );
        }
        line(&mut s, "} > \"$X11_ENV_FILE\"");
        line(&mut s, "chmod 0644 \"$X11_ENV_FILE\"");
        line(
            &mut s,
            "ARGS+=(--bind-ro=\"$X11_ENV_FILE:/etc/profile.d/00-nspawn-studio-x11.sh\")",
        );
        line(&mut s, "if [[ -n \"$DISPLAY_VALUE\" ]]; then");
        line(&mut s, "  ARGS+=(--setenv=DISPLAY=\"$DISPLAY_VALUE\")");
        line(&mut s, "fi");
        if cfg.x11 == X11Access::Xephyr {
            // Expose only the nested display's socket, not the host one.
            line(
                &mut s,
                "ARGS+=(--bind=\"/tmp/.X11-unix/X$XEPHYR_NUM:/tmp/.X11-unix/X$XEPHYR_NUM\")",
            );
        } else {
            line(&mut s, "if [[ -d /tmp/.X11-unix ]]; then");
            line(&mut s, "  ARGS+=(--bind=/tmp/.X11-unix)");
            line(&mut s, "fi");
        }
        if cfg.x11 == X11Access::Authority {
            line(&mut s, "if [[ -f \"$XAUTH\" ]]; then");
            line(&mut s, "  ARGS+=(--bind-ro=\"$XAUTH:/root/.Xauthority\")");
            line(&mut s, "  ARGS+=(--setenv=XAUTHORITY=/root/.Xauthority)");
            line(&mut s, "fi");
        }
    }

    if cfg.xhost_local {
        line(&mut s, "if command -v xhost >/dev/null 2>&1; then");
        line(&mut s, "  xhost +si:localuser:root >/dev/null 2>&1 || true");
        line(&mut s, "fi");
    }

    // --- Wayland ---
    if cfg.wayland {
        line(&mut s, "# --- Wayland ---");
        line(&mut s, "if [[ -S \"$RUNTIME_DIR/wayland-0\" ]]; then");
        line(&mut s, "  ARGS+=(--bind=\"$RUNTIME_DIR/wayland-0\")");
        line(&mut s, "  ARGS+=(--setenv=WAYLAND_DISPLAY=wayland-0)");
        line(&mut s, "  ARGS+=(--setenv=XDG_RUNTIME_DIR=\"$RUNTIME_DIR\")");
        line(&mut s, "fi");
    }

    // --- GPU ---
    if cfg.gpu {
        line(&mut s, "if [[ -d /dev/dri ]]; then");
        line(&mut s, "  ARGS+=(--bind=/dev/dri)");
        line(&mut s, "fi");
    }

    // --- audio ---
    if cfg.audio.pipewire {
        line(&mut s, "# --- PipeWire ---");
        line(&mut s, "if [[ -S \"$RUNTIME_DIR/pipewire-0\" ]]; then");
        line(&mut s, "  ARGS+=(--bind=\"$RUNTIME_DIR/pipewire-0\")");
        line(&mut s, "  ARGS+=(--setenv=PIPEWIRE_REMOTE=pipewire-0)");
        line(&mut s, "  ARGS+=(--setenv=XDG_RUNTIME_DIR=\"$RUNTIME_DIR\")");
        line(&mut s, "fi");
        line(&mut s, "if [[ -S \"$RUNTIME_DIR/pipewire-0-manager\" ]]; then");
        line(&mut s, "  ARGS+=(--bind=\"$RUNTIME_DIR/pipewire-0-manager\")");
        line(&mut s, "fi");
    }
    if cfg.audio.pipewire || cfg.audio.pulseaudio {
        line(&mut s, "# --- PulseAudio socket (native protocol) ---");
        line(&mut s, "if [[ -S \"$RUNTIME_DIR/pulse/native\" ]]; then");
        line(&mut s, "  ARGS+=(--bind=\"$RUNTIME_DIR/pulse/native\")");
        line(
            &mut s,
            "  ARGS+=(--setenv=PULSE_SERVER=\"unix:$RUNTIME_DIR/pulse/native\")",
        );
        line(&mut s, "fi");
    }
    if cfg.audio.alsa {
        line(&mut s, "# --- ALSA ---");
        line(&mut s, "if [[ -d /dev/snd ]]; then");
        line(&mut s, "  ARGS+=(--bind=/dev/snd)");
        line(&mut s, "fi");
    }

    // --- raw extra arguments ---
    for extra in &cfg.extra_args {
        let trimmed = extra.trim();
        if !trimmed.is_empty() {
            s.push_str("ARGS+=(");
            s.push_str(&shell_quote(trimmed));
            s.push_str(")\n");
        }
    }

    // --- run ---
    line(&mut s, "");
    line(&mut s, "# --- run -------------------------------------------------------------");
    match cfg.boot {
        BootMode::Boot => {
            line(&mut s, "RUNNER=(systemd-nspawn \"${ARGS[@]}\" \"$@\")");
        }
        BootMode::Command => {
            line(
                &mut s,
                &format!("CONTAINER_CMD_LINE={}", shell_quote(cfg.command.trim())),
            );
            line(&mut s, "read -r -a CONTAINER_CMD <<< \"$CONTAINER_CMD_LINE\"");
            line(
                &mut s,
                "RUNNER=(systemd-nspawn \"${ARGS[@]}\" -- \"${CONTAINER_CMD[@]}\" \"$@\")",
            );
        }
    }
    line(&mut s, "if [[ -n \"${XEPHYR_PID:-}\" ]]; then");
    line(&mut s, "  set +e");
    line(&mut s, "  \"${RUNNER[@]}\"");
    line(&mut s, "  status=$?");
    line(&mut s, "  kill \"$XEPHYR_PID\" 2>/dev/null");
    line(&mut s, "  wait \"$XEPHYR_PID\" 2>/dev/null");
    line(&mut s, "  exit $status");
    line(&mut s, "fi");
    line(&mut s, "exec \"${RUNNER[@]}\"");

    s
}

/// Generate an optional systemd unit that runs the launcher script.
pub fn generate_unit(cfg: &ContainerConfig, script_path: &str) -> String {
    let mut s = String::new();
    line(&mut s, "[Unit]");
    line(
        &mut s,
        &format!(
            "Description=Nspawn Studio container {}",
            comment_safe(&cfg.name)
        ),
    );
    line(&mut s, "Documentation=man:systemd-nspawn(1)");
    line(&mut s, "After=network.target");
    line(&mut s, "Before=shutdown.target");
    line(&mut s, "");
    line(&mut s, "[Service]");
    line(&mut s, "Type=simple");
    line(&mut s, &format!("ExecStart={}", script_path));
    line(&mut s, "Environment=NSPAWN_STUDIO_SERVICE=1");
    line(&mut s, "KillMode=mixed");
    line(&mut s, "KillSignal=SIGRTMIN+3");
    line(&mut s, "Restart=no");
    line(&mut s, "Delegate=yes");
    line(&mut s, "TasksMax=infinity");
    line(&mut s, "LimitNOFILE=16384");
    line(&mut s, "");
    line(&mut s, "[Install]");
    line(&mut s, "WantedBy=multi-user.target");
    s
}

/// Build the argv used to (re)create a debootstrap root filesystem.
pub fn debootstrap_argv(cfg: &ContainerConfig) -> Vec<String> {
    let spec = &cfg.debootstrap;
    let mut args: Vec<String> = Vec::new();
    args.push("debootstrap".to_string());
    if !spec.variant.trim().is_empty() {
        args.push(format!("--variant={}", spec.variant.trim()));
    }
    if !spec.include.is_empty() {
        args.push(format!("--include={}", spec.include.join(",")));
    }
    if !spec.components.is_empty() {
        args.push(format!("--components={}", spec.components.join(",")));
    }
    if let Some(keyring) = &spec.keyring {
        if !keyring.trim().is_empty() {
            args.push(format!("--keyring={}", keyring.trim()));
        }
    }
    args.push(format!("--arch={}", spec.arch.trim()));
    for extra in &spec.extra_args {
        let trimmed = extra.trim();
        if !trimmed.is_empty() {
            args.push(trimmed.to_string());
        }
    }
    args.push(spec.suite.trim().to_string());
    args.push(cfg.rootfs.to_string_lossy().into_owned());
    args.push(spec.mirror.trim().to_string());
    args
}

/// Build a shell script that provisions root and user accounts inside the
/// container's root filesystem. It is meant to be executed with
/// systemd-nspawn, for example:
///
/// ```text
/// systemd-nspawn --quiet -D /var/lib/machines/demo /bin/sh -c "<script>"
/// ```
pub fn provision_script(cfg: &ContainerConfig) -> String {
    let mut s = String::new();
    line(&mut s, "set -e");
    line(&mut s, "export DEBIAN_FRONTEND=noninteractive");
    line(&mut s, "echo '==> applying accounts inside the container'");

    let any_sudo = cfg.users.iter().any(|u| u.sudo);
    if any_sudo {
        line(&mut s, "getent group sudo >/dev/null 2>&1 || groupadd sudo");
    }

    if !cfg.root_password.is_empty() {
        line(&mut s, "echo '==> setting the root password'");
        let entry = format!("root:{}", cfg.root_password);
        line(
            &mut s,
            &format!("printf '%s\\n' {} | chpasswd", shell_quote(&entry)),
        );
        line(&mut s, "passwd -u root >/dev/null 2>&1 || true");
    }

    for user in &cfg.users {
        let name = user.name.trim();
        if name.is_empty() {
            continue;
        }
        let quoted = shell_quote(name);
        line(
            &mut s,
            &format!("echo '==> creating user {}'", name),
        );
        line(
            &mut s,
            &format!(
                "id -u {} >/dev/null 2>&1 || useradd -m -s /bin/bash {}",
                quoted, quoted
            ),
        );
        if !user.password.is_empty() {
            let entry = format!("{}:{}", name, user.password);
            line(
                &mut s,
                &format!("printf '%s\\n' {} | chpasswd", shell_quote(&entry)),
            );
        }
        line(
            &mut s,
            &format!("usermod -U {} >/dev/null 2>&1 || true", quoted),
        );
        if user.sudo {
            line(&mut s, &format!("usermod -aG sudo {}", quoted));
        }
    }

    if any_sudo {
        line(&mut s, "mkdir -p /etc/sudoers.d");
        line(
            &mut s,
            "printf '%s\\n' '%sudo ALL=(ALL:ALL) ALL' > /etc/sudoers.d/90-nspawn-studio",
        );
        line(&mut s, "chmod 0440 /etc/sudoers.d/90-nspawn-studio");
        line(&mut s, "if ! command -v sudo >/dev/null 2>&1; then");
        line(
            &mut s,
            "  (apt-get update -qq && apt-get install -y -qq sudo) >/dev/null 2>&1 || true",
        );
        line(&mut s, "fi");
    }

    line(&mut s, "echo '==> accounts applied'");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{AudioConfig, BindMount, NetworkConfig, PortForward, SecurityConfig};
    use std::path::PathBuf;

    fn base() -> ContainerConfig {
        let mut c = ContainerConfig::new(
            "demo",
            PathBuf::from("/var/lib/nspawn-studio/machines/demo"),
        );
        c.debootstrap.suite = "trixie".into();
        c
    }

    #[test]
    fn quote_simple_values() {
        assert_eq!(shell_quote("demo"), "demo");
        assert_eq!(shell_quote("/var/lib/x"), "/var/lib/x");
        assert_eq!(shell_quote("tcp:8080:80"), "tcp:8080:80");
        assert_eq!(shell_quote("a b"), "'a b'");
        assert_eq!(shell_quote(""), "''");
    }

    #[test]
    fn quote_escapes_single_quotes() {
        assert_eq!(shell_quote("it's"), "'it'\\''s'");
    }

    #[test]
    fn expand_tilde_uses_home() {
        std::env::set_var("HOME", "/root");
        assert_eq!(expand_tilde("~/x"), "/root/x");
        assert_eq!(expand_tilde("/abs"), "/abs");
    }

    #[test]
    fn script_starts_with_shebang_and_is_strict() {
        let s = generate_script(&base());
        assert!(s.starts_with("#!/usr/bin/env bash\n"));
        assert!(s.contains("set -euo pipefail"));
        assert!(s.contains("ARGS+=(\"--machine=$NAME\")"));
        assert!(s.contains("ARGS+=(\"--directory=$ROOTFS\")"));
    }

    #[test]
    fn boot_mode_adds_boot_flag() {
        let s = generate_script(&base());
        assert!(s.contains("ARGS+=(-b)"));
        assert!(s.contains("RUNNER=(systemd-nspawn \"${ARGS[@]}\" \"$@\")"));
        assert!(s.contains("exec \"${RUNNER[@]}\""));
    }

    #[test]
    fn command_mode_runs_command() {
        let mut c = base();
        c.boot = BootMode::Command;
        c.command = "/bin/bash -l".into();
        let s = generate_script(&c);
        assert!(!s.contains("ARGS+=(-b)"));
        assert!(s.contains("CONTAINER_CMD_LINE='/bin/bash -l'"));
        assert!(s.contains("read -r -a CONTAINER_CMD"));
        assert!(s.contains("-- \""));
        assert!(s.contains("CONTAINER_CMD[@]"));
    }

    #[test]
    fn xephyr_mode_starts_a_nested_server() {
        let mut c = base();
        c.x11 = X11Access::Xephyr;
        c.xephyr_screen = "1024x768".into();
        let s = generate_script(&c);
        assert!(s.contains("command -v Xephyr"));
        assert!(s.contains("-screen 1024x768"));
        assert!(s.contains("-ac -noreset"));
        assert!(s.contains("XEPHYR_PID=$!"));
        assert!(s.contains("/tmp/.X11-unix/X$XEPHYR_NUM"));
        assert!(s.contains("kill \"$XEPHYR_PID\""));
        assert!(s.contains("export DISPLAY="));
    }

    #[test]
    fn hostname_flag_is_emitted() {
        let mut c = base();
        c.hostname = Some("box".into());
        assert!(generate_script(&c).contains("--hostname=box"));
    }

    #[test]
    fn security_flags_are_emitted() {
        let mut c = base();
        c.security = SecurityConfig::recommended();
        c.security.mask.push("/srv/secret".into());
        let s = generate_script(&c);
        assert!(s.contains("ARGS+=(-U)"));
        assert!(s.contains("--no-new-privileges=yes"));
        assert!(s.contains("--drop-capability=CAP_SYS_MODULE"));
        assert!(s.contains("--system-call-filter=~@clock"));
        assert!(s.contains("--inaccessible=/srv/secret"));
    }

    #[test]
    fn readonly_and_ephemeral_and_tmpfs() {
        let mut c = base();
        c.security.read_only = true;
        c.security.ephemeral = true;
        c.security.tmpfs.push("/tmp".into());
        let s = generate_script(&c);
        assert!(s.contains("ARGS+=(--read-only)"));
        assert!(s.contains("ARGS+=(--ephemeral)"));
        assert!(s.contains("--tmpfs=/tmp"));
    }

    #[test]
    fn network_modes() {
        let mut c = base();
        c.network = NetworkConfig {
            mode: NetworkMode::Private,
            bridge: None,
            port_forwards: vec![PortForward::new("tcp", 8080, 80)],
        };
        let s = generate_script(&c);
        assert!(s.contains("ARGS+=(--private-network)"));
        assert!(s.contains("--port=tcp:8080:80"));

        c.network = NetworkConfig {
            mode: NetworkMode::Veth,
            bridge: Some("br0".into()),
            port_forwards: vec![],
        };
        let s = generate_script(&c);
        assert!(s.contains("ARGS+=(--network-veth)"));
        assert!(s.contains("--network-bridge=br0"));
    }

    #[test]
    fn host_network_emits_nothing_network_specific() {
        let s = generate_script(&base());
        assert!(!s.contains("--private-network"));
        assert!(!s.contains("--network-veth"));
        assert!(!s.contains("--port="));
    }

    #[test]
    fn bind_mounts_are_emitted_with_mode() {
        let mut c = base();
        c.mounts.push(BindMount::new("/home/user", "/mnt/home", true));
        c.mounts.push(BindMount::new("/srv/data", "/data", false));
        let s = generate_script(&c);
        assert!(s.contains("--bind-ro=/home/user:/mnt/home"));
        assert!(s.contains("--bind=/srv/data:/data"));
    }

    #[test]
    fn host_root_preset_is_readonly_bind() {
        let mut c = base();
        c.mounts.push(BindMount::new("/", "/mnt/host", true));
        let s = generate_script(&c);
        assert!(s.contains("--bind-ro=/:/mnt/host"));
    }

    #[test]
    fn x11_authority_block() {
        let mut c = base();
        c.x11 = X11Access::Authority;
        let s = generate_script(&c);
        assert!(s.contains("--setenv=DISPLAY"));
        assert!(s.contains("--bind=/tmp/.X11-unix"));
        assert!(s.contains("--bind-ro=\"$XAUTH:/root/.Xauthority\""));
        assert!(s.contains("--setenv=XAUTHORITY=/root/.Xauthority"));
    }

    #[test]
    fn x11_sets_the_login_environment() {
        let mut c = base();
        c.x11 = X11Access::Authority;
        let s = generate_script(&c);
        assert!(s.contains("profile.d/00-nspawn-studio-x11.sh"));
        assert!(s.contains("export DISPLAY="));
        assert!(s.contains("export XAUTHORITY=/root/.Xauthority"));
    }

    #[test]
    fn x11_none_has_no_block() {
        let s = generate_script(&base());
        assert!(!s.contains("--setenv=DISPLAY"));
        assert!(!s.contains("/tmp/.X11-unix"));
    }

    #[test]
    fn x11_socket_only_has_no_xauthority() {
        let mut c = base();
        c.x11 = X11Access::Socket;
        let s = generate_script(&c);
        assert!(s.contains("--bind=/tmp/.X11-unix"));
        assert!(!s.contains("XAUTHORITY=/root/.Xauthority"));
    }

    #[test]
    fn audio_backends() {
        let mut c = base();
        c.audio = AudioConfig {
            pipewire: true,
            pulseaudio: true,
            alsa: true,
        };
        let s = generate_script(&c);
        assert!(s.contains("pipewire-0"));
        assert!(s.contains("PULSE_SERVER=\"unix:$RUNTIME_DIR/pulse/native\""));
        assert!(s.contains("ARGS+=(--bind=/dev/snd)"));
        assert_eq!(
            s.matches("ARGS+=(--bind=\"$RUNTIME_DIR/pulse/native\")")
                .count(),
            1
        );
    }

    #[test]
    fn gpu_and_wayland() {
        let mut c = base();
        c.gpu = true;
        c.wayland = true;
        let s = generate_script(&c);
        assert!(s.contains("--bind=/dev/dri"));
        assert!(s.contains("wayland-0"));
        assert!(s.contains("WAYLAND_DISPLAY=wayland-0"));
    }

    #[test]
    fn resolv_and_timezone_flags() {
        let mut c = base();
        c.timezone = crate::model::TimezoneMode::Bind;
        let s = generate_script(&c);
        assert!(s.contains("--resolv-conf=auto"));
        assert!(s.contains("--timezone=bind"));
    }

    #[test]
    fn extra_args_are_quoted() {
        let mut c = base();
        c.extra_args.push("--setenv=FOO=bar baz".into());
        let s = generate_script(&c);
        assert!(s.contains("ARGS+=('--setenv=FOO=bar baz')"));
    }

    #[test]
    fn debootstrap_argv_shape() {
        let c = base();
        let argv = debootstrap_argv(&c);
        assert_eq!(argv[0], "debootstrap");
        assert!(argv.contains(&"--variant=minbase".to_string()));
        assert!(argv.contains(&"--arch=amd64".to_string()));
        let suite = argv.iter().position(|a| a == "trixie").unwrap();
        let rootfs = argv.iter().position(|a| a.ends_with("/demo")).unwrap();
        assert!(suite < rootfs);
        assert_eq!(
            argv.iter()
                .filter(|a| a.as_str() == "http://deb.debian.org/debian")
                .count(),
            1
        );
    }

    #[test]
    fn provision_script_sets_root_and_users() {
        let mut c = base();
        c.root_password = "s3cret".into();
        c.users
            .push(crate::model::ContainerUser::new("alice", "wonder", true));
        c.users
            .push(crate::model::ContainerUser::new("bob", "builder", false));
        let s = provision_script(&c);
        assert!(s.contains("root:s3cret"));
        assert!(s.contains("chpasswd"));
        assert!(s.contains("useradd -m -s /bin/bash alice"));
        assert!(s.contains("alice:wonder"));
        assert!(s.contains("usermod -aG sudo alice"));
        assert!(!s.contains("usermod -aG sudo bob"));
        assert!(s.contains("/etc/sudoers.d/90-nspawn-studio"));
        assert!(s.contains("getent group sudo"));
    }

    #[test]
    fn provision_script_is_empty_without_accounts() {
        let c = base();
        let s = provision_script(&c);
        assert!(!s.contains("chpasswd"));
        assert!(!s.contains("useradd"));
        assert!(!s.contains("sudoers"));
    }

    #[test]
    fn provision_script_quotes_awkward_passwords() {
        let mut c = base();
        c.root_password = "p'w".into();
        c.users
            .push(crate::model::ContainerUser::new("alice", "a b", true));
        let s = provision_script(&c);
        assert!(s.contains("chpasswd"));
        // The generated script must remain valid shell.
        let dir = std::env::temp_dir();
        let path = dir.join(format!("nspawn-provision-{}.sh", crate::model::now_unix()));
        std::fs::write(&path, &s).unwrap();
        let out = std::process::Command::new("bash")
            .arg("-n")
            .arg(&path)
            .output()
            .unwrap();
        assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn systemd_unit_is_valid_ini() {
        let c = base();
        let unit = generate_unit(&c, "/var/lib/nspawn-studio/scripts/demo.sh");
        assert!(unit.contains("[Unit]"));
        assert!(unit.contains("[Service]"));
        assert!(unit.contains("ExecStart=/var/lib/nspawn-studio/scripts/demo.sh"));
        assert!(unit.contains("Environment=NSPAWN_STUDIO_SERVICE=1"));
        assert!(unit.contains("[Install]"));
    }
}
